# -*- coding: utf-8 -*-
"""2-Proposition_solution_exercices_supplementaire_bonus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDKf3ymfGZCyHlOHt_P-AqA454oolbBM
"""

# ============================================================
# Exercice 1 – Bonjour, utilisateur  ----
# Description : Demander à l'utilisateur son prénom et son âge, puis afficher un message de bienvenue personnalisé.
# ============================================================
# Solution
prenom = input("Quel est votre prénom ? ")
age = input("Quel est votre âge ? ")
print(f"Bonjour {prenom}, vous avez {age} ans.")


# ============================================================
# Exercice 2 – Opérations simples ----
# Description : Stocker deux nombres dans des variables, puis afficher leur somme, leur produit, leur division entière et réelle.
# ============================================================
# Solution
a = 10
b = 3
print("Somme :", a + b)
print("Produit :", a * b)
print("Division entière :", a // b)
print("Division réelle :", a / b)


# ============================================================
# Exercice 3 – Pair ou impair ----
# Description : Demander un nombre à l’utilisateur et afficher s’il est pair ou impair.
# ============================================================
# Solution
nombre = int(input("Entrez un nombre : "))
if nombre % 2 == 0:
    print("Ce nombre est pair.")
else:
    print("Ce nombre est impair.")


# ============================================================
# Exercice 4 – Le plus grand de trois ----
# Description : Demander trois nombres à l’utilisateur et afficher le plus grand.
# ============================================================
# Solution 1 – avec conditions
a = int(input("Nombre 1 : "))
b = int(input("Nombre 2 : "))
c = int(input("Nombre 3 : "))
if a >= b and a >= c:
    print("Le plus grand est :", a)
elif b >= a and b >= c:
    print("Le plus grand est :", b)
else:
    print("Le plus grand est :", c)

# Solution 2 – avec max()
print("Le plus grand est :", max(a, b, c))


# ============================================================
# Exercice 5 – Compter jusqu’à N ----
# Description : Demander un entier n et afficher tous les nombres de 1 à n.
# ============================================================
# Solution
n = int(input("Entrez un nombre : "))
for i in range(1, n+1):
    print(i)


# ============================================================
# Exercice 6 – Jeu du mot de passe ----
# Description : Tant que l’utilisateur ne tape pas 'python123', lui redemander un mot de passe.
# ============================================================
# Solution
mot_de_passe = ""
while mot_de_passe != "python123":
    mot_de_passe = input("Entrez le mot de passe : ")
print("Accès autorisé !")


# ============================================================
# Exercice 7 – Table de multiplication ----
# Description : Créer une fonction affiche_table(n) qui affiche la table de multiplication de n de 1 à 10.
# ============================================================
# Solution
def affiche_table(n):
    for i in range(1, 11):
        print(f"{n} x {i} = {n*i}")

# Exemple d'appel
affiche_table(5)


# ============================================================
# Exercice 8 – Moyenne d’une liste ----
# Description : Créer une fonction moyenne(notes) qui retourne la moyenne d’une liste de notes.
# ============================================================
# Solution
def moyenne(notes):
    return sum(notes) / len(notes)

# Exemple
print(moyenne([12, 15, 14]))


# ============================================================
# Exercice 9 – Compter les voyelles ----
# Description : Créer une fonction compte_voyelles(texte) qui retourne le nombre de voyelles dans une chaîne.
# ============================================================
# Solution
def compte_voyelles(texte):
    voyelles = "aeiouyAEIOUY"
    compteur = 0
    for lettre in texte:
        if lettre in voyelles:
            compteur += 1
    return compteur

# Exemple
print(compte_voyelles("Bonjour tout le monde"))


# ============================================================
# Exercice 10 – Carnet de contacts ----
# Description : Créer un dictionnaire contacts et permettre d'ajouter des noms et numéros.
# ============================================================
# Solution
contacts = {}
while True:
    nom = input("Entrez un nom (ou 'fin' pour arrêter) : ")
    if nom == "fin":
        break
    numero = input(f"Entrez le numéro de {nom} : ")
    contacts[nom] = numero

print("Carnet de contacts :")
for nom, numero in contacts.items():
    print(f"{nom} : {numero}")


# ============================================================
# Exercice 11 – Statistiques de notes ----
# Description : Créer un dictionnaire d’élèves avec leurs notes. Calculer la moyenne par élève et afficher l’élève avec la meilleure moyenne.
# ============================================================
# Solution
eleves = {
    "Alice": [12, 15, 14],
    "Bob": [9, 13, 11],
    "Clara": [15, 18, 17]
}

meilleure_moyenne = 0
meilleur_eleve = ""

for nom, notes in eleves.items():
    moyenne = sum(notes) / len(notes)
    print(f"{nom} a une moyenne de {moyenne:.2f}")
    if moyenne > meilleure_moyenne:
        meilleure_moyenne = moyenne
        meilleur_eleve = nom

print(f"Le meilleur élève est {meilleur_eleve} avec {meilleure_moyenne:.2f} de moyenne.")


# ============================================================
# Exercice 12 – Dé aléatoire ----
# Description : Simuler un lancer de dé (1 à 6) jusqu’à obtenir un 6. Compter le nombre de lancers.
# ============================================================
# Solution
import random
class SimuLancerDe():
    def __init__(self):
        self.compteur = 0
        self.resultat = 0
        self.succes = False
    def lancer(self):
        self.resultat = random.randint(1,6)
        self.compteur += 1
        print(f"Lancer {self.compteur}, resultat : {self.resultat}")
        if self.resultat == 6:
            self.succes = True
    def jouer(self):
        while not self.succes:
            self.lancer()
        print(f"Nombre de lancers effectués : {self.compteur}")

uneSimu=SimuLancerDe()
uneSimu.jouer()
# Solution alternative simple
import random

compteur = 0
resultat = 0

while resultat != 6:
    resultat = random.randint(1, 6)
    print("Lancer :", resultat)
    compteur += 1

print(f"Nombre de lancers nécessaires : {compteur}")


# ============================================================
# Exercice 13 – Devine le nombre ----
# Description : Choisir un nombre aléatoire entre 1 et 100. L’utilisateur a 10 tentatives pour le deviner avec des indices.
# ============================================================
# Solution
import random
class SimuDevineNb():
    def __init__(self):
        self.nb_essaye = 0
        self.nb_aleatoire = random.randint(1,100)
        self.tentatives_restantes = 10
        self.succes = False
    def deviner(self):
        print(f"Il vous reste {self.tentatives_restantes} tentatives.")
        self.nb_essaye = int(input("Devinez le nombre (entre 1 et 100) : "))
        self.tentatives_restantes -= 1
        self.succes = self.nb_aleatoire == self.nb_essaye
    def jouer(self):
        while not self.succes and self.tentatives_restantes > 0:
            self.deviner()
            if self.succes:
                print("Bravo ! Vous avez deviné le nombre.")
            else:
                if self.nb_essaye < self.nb_aleatoire:
                    print("Trop petit.")
                else:
                    print("Trop grand.")
        if self.tentatives_restantes == 0:
            print(f"Dommage, le nombre était {self.nb_aleatoire}.")

uneSimu=SimuDevineNb()
uneSimu.jouer()

# Solution alternative simple

import random

secret = random.randint(1, 100)
tentatives = 10

for i in range(tentatives):
    guess = int(input("Devinez le nombre : "))
    if guess < secret:
        print("Trop petit.")
    elif guess > secret:
        print("Trop grand.")
    else:
        print("Bravo ! Vous avez deviné.")
        break
else:
    print(f"Dommage, le nombre était {secret}.")



# ============================================================
# Exercice 14 – Analyse de texte ----
# Description : Demander une phrase à l’utilisateur, puis afficher nombre de mots, mot le plus long, fréquence des lettres.
# ============================================================
# Solution
texte = input("Entrez une phrase : ")

# Nombre de mots
mots = texte.split()
print("Nombre de mots :", len(mots))

# Mot le plus long
mot_plus_long = max(mots, key=len)
print("Mot le plus long :", mot_plus_long)
        #EXEMPLES D'UTILISATION DE max() AVEC KEY
# Personne la plus âgée
personnes = [("Alice", 34), ("Bob", 19), ("Charlie", 45)]
plus_aged = max(personnes, key=lambda p: p[1])     # → ('Charlie', 45)

# Produit le plus cher
produits = {"stylo": 1.2, "cahier": 3.5, "sac": 29.9}
plus_cher = max(produits, key=produits.get)        # → "sac"

# Fichier le plus récent (par date de modification)
import os
fichiers = ["a.txt", "b.py", "readme.md"]
plus_recente = max(fichiers, key=os.path.getmtime)

# Fréquence des lettres
frequences = {}
for lettre in texte:
    if lettre.isalpha():
        lettre = lettre.lower()
        frequences[lettre] = frequences.get(lettre, 0) + 1

print("Fréquence des lettres :")
for lettre, freq in sorted(frequences.items()):
    print(f"{lettre} : {freq}")