# -*- coding: utf-8 -*-
"""1-exercices_supplementaires_python_et_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1qh7aSklFbJgfPY48iu3ekKdD-wHaS3

# Exercices supplémentaires :

Thèmes :

1. Conditions et logique

2. Boucles

3. Fonctions

4. Listes et tuples

5. Chaînes de caractères

6. Dictionnaires et ensembles

7. Compréhensions de liste

8. Notions orientées objet (OOP)

### Exercices modules EDA

9. Modules et importations

10. Manipulation de numpy.array

11. Manipulation de pandas (opérations de base)

# THEME 1 : Conditions et logique
"""

# Exercice 1 (*) : Pair ou impair
n = 7
# TODO: Affiche si n est pair ou impair

# Exercice 2 (*) : Majeur ou mineur
age = 20
# TODO: Affiche "Majeur" si age >= 18, sinon "Mineur"

# Exercice 3 (**) : Nombre positif, négatif ou nul
nombre = -3
# TODO: Affiche si le nombre est positif, négatif ou nul

# Exercice 4 (***) : Le plus grand de trois nombres
x, y, z = 5, 9, 3
# TODO: Affiche le plus grand

# Exercice 5 (****) : Validation d'identité
nom = "Alice"
age = 25
# TODO: Vérifie si nom est "Alice" et age > 18, affiche "Accès autorisé"

# Exercice 6 (*****) : Jeu de devinette avec conditions
# TODO: Simule un jeu où l'utilisateur doit deviner un nombre secret avec des if imbriqués

# --- Solutions ---
# Ex1
# if n % 2 == 0:
#     print("Pair")
# else:
#     print("Impair")

# Ex2
# print("Majeur" if age >= 18 else "Mineur")

# Ex3
# if nombre > 0:
#     print("Positif")
# elif nombre < 0:
#     print("Négatif")
# else:
#     print("Nul")

# Ex4
# print(max(x, y, z))

# Ex5
# if nom == "Alice" and age > 18:
#     print("Accès autorisé")
# else:
#     print("Accès refusé")

# Ex6
# secret = 7
# guess = int(input("Devine le nombre (entre 1 et 10) : "))
# if guess == secret:
#     print("Bravo !")
# elif guess < secret:
#     print("Trop petit")
# else:
#     print("Trop grand")

"""# THEME 2 : Boucles

"""

# Exercice 1 (*) : Compter jusqu'à 10

# Exercice 2 (*) : Somme des n premiers entiers

# Exercice 3 (**) : Affichage des pairs entre 1 et 20

# Exercice 4 (**) : Factorielle d’un nombre
n = 5
# TODO: Calcule la factorielle de n (la factorielle de 5 est 5*4*3*2*1)

# Exercice 5 (***) : Compter les voyelles dans une chaîne
chaine = "Exercice"

# Exercice 6 (****) : Table de multiplication
n = 7
# TODO: Affiche la table de multiplication de n

# Exercice 7 (*****) : Trouver tous les diviseurs d’un nombre

# --- Solutions ---
# Ex1
# for i in range(1, 11):
#     print(i)

# Ex2
# n = 10
# total = sum(range(1, n+1))
# print(total)

# Ex3
# for i in range(2, 21, 2):
#     print(i)

# Ex4
# result = 1
# for i in range(1, n+1):
#     result *= i
# print(result)

# Ex5
# count = 0
# for char in chaine.lower():
#     if char in "aeiouy":
#         count += 1
# print(count)

# Ex6
# for i in range(1, 11):
#     print(f"{n} x {i} = {n*i}")

# Ex7
# nombre = 12
# for i in range(1, nombre + 1):
#     if nombre % i == 0:
#         print(i)

"""
# THEME 3 : Fonctions


"""

# Exercice 1 (*) : Fonction qui retourne le carré d’un nombre

# Exercice 2 (*) : Fonction qui dit bonjour à un nom donné

# Exercice 3 (**) : Fonction pour vérifier la majorité

# Exercice 4 (***) : Fonction qui retourne le max de trois nombres

# Exercice 6 (*****) : Fonction de validation d'un mot de passe (longueur, caractère spécial, chiffre...)

# --- Solutions ---
# Ex1
# def carre(x):
#     return x ** 2

# Ex2
# def bonjour(nom):
#     print(f"Bonjour {nom}!")

# Ex3
# def est_majeur(age):
#     return age >= 18

# Ex4
# def maximum(a, b, c):
#     return max(a, b, c)


# Ex6
# def mot_de_passe_valide(mdp):
#     return len(mdp) >= 8 and any(c.isdigit() for c in mdp) and any(c in "!@#$%^&*" for c in mdp)

"""# THEME 4 : Listes et tuples"""

liste = [2,4,1]

liste.append(5)
liste

import numpy as np

ar = np.array([3,2,1])
ar.dtype

# Exercice 1 (*) : Accéder aux éléments d’une liste
# ma_liste = [1, 2, 3]
# TODO: Affiche le premier élément

# Exercice 2 (*) : Ajouter/Supprimer un élément
# TODO: Ajoute 4 à la liste et enlève 2

# Exercice 3 (**) : Calculer la moyenne
notes = [10, 15, 12]
# TODO: Calcule la moyenne des notes

# Exercice 4 (**) : Compter les occurrences d’un mot
mots = ["bonjour", "salut", "bonjour"]
# TODO: Compte combien de fois "bonjour" apparaît

# Exercice 5 (***) : Trier une liste sans utiliser sort()
lst = [5, 2, 8, 1]
# TODO: Trie la liste manuellement (tri par sélection ou autre)

# Exercice 6 (****) : Trouver les éléments communs entre deux listes
a = [1, 2, 3]
b = [2, 3, 4]
# TODO: Affiche les éléments communs

# Exercice 7 (*****) : Créer une matrice 3x3 avec des listes imbriquées et afficher la diagonale principale
matrice = [[1,2,3],[4,5,6],[7,8,9]]
# TODO: Affiche les éléments de la diagonale principale

# --- Solutions ---
# Ex1
# ma_liste = [1, 2, 3]
# print(ma_liste[0])

# Ex2
# ma_liste.append(4)
# ma_liste.remove(2)

# Ex3
# notes = [10, 15, 12]
# print(sum(notes) / len(notes))

# Ex4
# mots = ["bonjour", "salut", "bonjour"]
# print(mots.count("bonjour"))

# Ex5
# lst = [5, 2, 8, 1]
# for i in range(len(lst)):
#     for j in range(i + 1, len(lst)):
#         if lst[i] > lst[j]:
#             lst[i], lst[j] = lst[j], lst[i]
# print(lst)

# Ex6
# Solution 1
# a = [1, 2, 3]
# b = [2, 3, 4]
# communs = []
# for element in a:
#     if element in b:
#         communs.append(element)
# print(communs)


# Solution 2 (mais utilise des set pas au programme)
# a = [1, 2, 3]
# b = [2, 3, 4]
# communs = list(set(a) & set(b))
# print(communs)




# Ex7
# matrice = [[1,2,3],[4,5,6],[7,8,9]]
# for i in range(3):
#     print(matrice[i][i])

"""# THEME 5 : Chaînes de caractères

"""

# Ex1
# Énoncé : Écris un programme qui affiche chaque lettre du mot "Python" sur une ligne différente.

# Ex2
# Énoncé : Affiche "bonjour" en majuscules, puis "BONJOUR" en minuscules.


# Ex3
# Énoncé : Compte le nombre de voyelles dans le mot "Bonjour".


# Ex4
# Énoncé : Vérifie si le mot "radar" est un palindrome (se lit de la même façon à l'endroit et à l'envers).


# Ex5
# Énoncé : Sépare la phrase "Bonjour tout le monde" en mots.


# Ex6
# Énoncé : Écris une fonction qui chiffre un message en utilisant le chiffrement de César avec un décalage donné.
# Par exemple, pour "abc" avec un décalage de 2, le résultat doit être "cde".


# --- Solutions ---
# Ex1
# for c in "Python":
#     print(c)

# Ex2
# print("bonjour".upper())
# print("BONJOUR".lower())

# Ex3
# print(sum(1 for c in texte.lower() if c in "aeiouy"))

# Ex4
# print(mot == mot[::-1])

# Ex5
# print(phrase.split())

# Ex6
# def cesar(msg, decalage):
#     return ''.join(chr((ord(c) - 97 + decalage) % 26 + 97) if c.isalpha() else c for c in msg.lower())
# print(cesar("abc", 2))

"""# THEME 6 : Dictionnaires et ensembles

"""

# Exercice 1 (*) : Créer un dictionnaire simple (clé-valeur)
dico = {"nom": "Alice", "âge": 30}

# Exercice 2 (*) : Afficher toutes les clés et valeurs
# TODO: Itérer sur les éléments du dictionnaire et les afficher

# Exercice 3 (**) : Compter la fréquence des lettres dans une chaîne
texte = "bonjour"
# TODO: Compte combien de fois chaque lettre apparaît

# Exercice 4 (***) : Fusionner deux dictionnaires
a = {"x": 1, "y": 2}
b = {"y": 3, "z": 4}
# TODO: Fusionner a et b (b écrase les doublons)


# Exercice 6 (*****) : Créer un dictionnaire inversé (valeur => clé)
d = {"a": 1, "b": 2, "c": 3}
# TODO: Inverser le dictionnaire en valeur:clé

# --- Solutions ---
# Ex1
# dico = {"nom": "Alice", "âge": 30}

# Ex2
# for cle, valeur in dico.items():
#     print(cle, valeur)

# Ex3
# freq = {}
# for lettre in texte:
#     freq[lettre] = freq.get(lettre, 0) + 1
# print(freq)

# Ex4
# fusion = {**a, **b}
# print(fusion)


# Ex6
# inverse = {v: k for k, v in d.items()}
# print(inverse)

"""# THEME 7 : Compréhensions de liste

"""

# Exercice 1 (*) : Carrés des entiers de 0 à 9
# TODO: Crée une liste contenant les carrés des entiers de 0 à 9

# Exercice 2 (**) : Tous les nombres pairs entre 1 et 20
# TODO: Liste des nombres pairs entre 1 et 20

# Exercice 3 (***) : Extraire les mots de plus de 3 lettres d’une liste
mots = ["le", "chat", "bleu", "est", "beau"]
# TODO: Extraire les mots avec plus de 3 lettres

# Exercice 4 (****) : Appliquer une fonction à tous les éléments
nombres = [1, 2, 3, 4]
# TODO: Ajouter 10 à chaque nombre avec une compréhension

# Exercice 5 (*****) : Créer une matrice 2D avec des compréhensions imbriquées
# TODO: Crée une matrice 3x3 où chaque cellule vaut i * j

# --- Solutions ---
# Ex1
# carres = [x**2 for x in range(10)]
# print(carres)

# Ex2
# pairs = [x for x in range(1, 21) if x % 2 == 0]
# print(pairs)

# Ex3
# longs_mots = [mot for mot in mots if len(mot) > 3]
# print(longs_mots)

# Ex4
# ajoute_dix = [x + 10 for x in nombres]
# print(ajoute_dix)

# Ex5
# matrice = [[i * j for j in range(3)] for i in range(3)]
# print(matrice)

"""# THEME 8 : Programmation orientée objet

"""

# Exercice 1 (*) : Créer une classe Personne avec nom
# TODO: Crée une classe avec un attribut nom

# Exercice 2 (**) : Ajouter une méthode saluer()
# TODO: La méthode affiche "Bonjour, je m'appelle NOM"

# Exercice 3 (***) : Créer une classe CompteBancaire avec dépôt et retrait

# Exercice 4 (****) : Héritage : classe Étudiant hérite de Personne

# Exercice 5 (*****) : Système d'inventaire avec plusieurs objets interconnectés (jeu, bibliothèque...)

# --- Solutions ---
# Ex1 & Ex2
# class Personne:
#     def __init__(self, nom):
#         self.nom = nom
#     def saluer(self):
#         print(f"Bonjour, je m'appelle {self.nom}")

# Ex3
# class CompteBancaire:
#     def __init__(self, solde=0):
#         self.solde = solde
#     def depot(self, montant):
#         self.solde += montant
#     def retrait(self, montant):
#         self.solde -= montant
#     def afficher(self):
#         print(f"Solde: {self.solde}")

# Ex4
# class Etudiant(Personne):
#     def __init__(self, nom, etudes):
#         super().__init__(nom)
#         self.etudes = etudes

# Ex5
# class Objet:
#     def __init__(self, nom, type):
#         self.nom = nom
#         self.type = type
# class Inventaire:
#     def __init__(self):
#         self.objets = []
#     def ajouter(self, objet):
#         self.objets.append(objet)

"""# THEME 9 : Modules et importations

"""

# Exercice 1 (*) : Utiliser random.randint()
# TODO: Affiche un nombre aléatoire entre 1 et 10

# Exercice 2 (**) : Utiliser math.sqrt()
# TODO: Affiche la racine carrée d’un nombre

# Exercice 4 (****) : Générer une série de nombres aléatoires et les trier

# Exercice 5 (*****) : Chronométrer une exécution avec time() (regarder la documentation)

# --- Solutions ---
# import random
# print(random.randint(1, 10))

# import math
# print(math.sqrt(25))


# liste = [random.randint(1, 100) for _ in range(10)]
# print(sorted(liste))

# import time
# start = time.time()
# sum(range(1000000))
# print("Temps:", time.time() - start)

"""# THEME 10 : numpy.array

"""

# Exercice 1 (*) : Créer un array 1D, vérifier shape et dtype
# TODO: Crée un tableau 1D avec numpy et affiche sa forme et son type de données

# Exercice 2 (*) : Array rempli de zéros, de uns
# TODO: Crée un tableau 2x2 de zéros et un autre 3x1 de uns

# Exercice 3 (**) : Redimensionner un array
# TODO: Crée un tableau de 6 éléments et transforme-le en matrice 2x3

# Exercice 4 (***) : Opérations vectorielles (addition, multiplication)
# TODO: Crée un tableau de taille 10 d'éléments aléatoires entre 1 et 10 et effectue les opérations vectorielles :
# - ajout de 10 a chaque element
# - multiplie par 2 chaque element
# - ajout de 10 a chaque element
# - ajout de 10 à tous les éléments plus grand que 5 et multiplie par 2 tous les élements plus petits que 5


# Exercice 5 (****) : Produit matriciel
# TODO: Multiplie deux matrices compatibles

# Exercice 6 (*****) : Appliquer une fonction mathématique à tous les éléments
# TODO: Applique np.sin() à un tableau d’angles

# --- Solutions ---
# import numpy as np

# Ex1
# arr = np.array([1, 2, 3])
# print(arr.shape, arr.dtype)

# Ex2
# print(np.zeros((2, 2)))
# print(np.ones((3, 1)))

# Ex3
# arr = np.arange(6)
# arr2 = arr.reshape((2, 3))
# print(arr2)

# Ex4
# arr = np.array([1, 2, 3])
# print(arr + 10)
# print(arr * 2)

# Ex5
# A = np.array([[1, 2], [3, 4]])
# B = np.array([[2, 0], [1, 2]])
# print(np.dot(A, B))

# Ex6
# angles = np.array([0, np.pi / 2, np.pi])
# print(np.sin(angles))

"""# THEME 11 : pandas de base

https://www.kaggle.com/learn/pandas
"""



"""# Thème 12 : projet"""

# Commented out IPython magic to ensure Python compatibility.
# %pwd

import pandas as pd
import numpy as np


df_raw = pd.read_csv("Speed+Dating+Data.csv", encoding='cp1252')
np.where(np.array(df_raw.iloc[0]) =="Law")

df_raw.iloc[:,34].value_counts().head(10)